-- drop tables

DROP TABLE IF EXISTS user_ CASCADE ;
DROP TABLE IF EXISTS auth CASCADE ;
DROP TABLE IF EXISTS user_follows_user CASCADE ;
DROP TABLE IF EXISTS theme CASCADE ;
DROP TABLE IF EXISTS changeset CASCADE ;
DROP TABLE IF EXISTS layer CASCADE ;
DROP TABLE IF EXISTS user_collaborates_layer CASCADE ;
DROP TABLE IF EXISTS user_follows_layer CASCADE ;
DROP TABLE IF EXISTS feature CASCADE ;
DROP TABLE IF EXISTS version_feature CASCADE ;
DROP TABLE IF EXISTS review CASCADE ;
DROP TABLE IF EXISTS notification CASCADE ;
DROP TABLE IF EXISTS user_notification CASCADE ;
DROP TABLE IF EXISTS bulk_import CASCADE ;

DROP TABLE IF EXISTS layer_1001 CASCADE ;
DROP TABLE IF EXISTS layer_1002 CASCADE ;
DROP TABLE IF EXISTS layer_1003 CASCADE ;
DROP TABLE IF EXISTS layer_1004 CASCADE ;
DROP TABLE IF EXISTS layer_1005 CASCADE ;
DROP TABLE IF EXISTS layer_1006 CASCADE ;


