-- MySQL Script generated by MySQL Workbench
-- Ter 24 Abr 2018 17:54:12 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_` (
  `id` INT NOT NULL,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `username` TEXT NOT NULL,
  `name` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `is_email_valid` TINYINT(1) NOT NULL,
  `terms_agreed` TINYINT(1) NOT NULL,
  `login_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`layer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`layer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`layer` (
  `id` INT NOT NULL,
  `table_name` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NULL,
  `source_author_name` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `removed_at` TIMESTAMP NULL,
  `is_published` TINYINT(1) NULL,
  `fk_user_id_author` INT NOT NULL,
  `fk_user_id_published_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_user1_idx` (`fk_user_id_author` ASC),
  INDEX `fk_layer_user_1_idx` (`fk_user_id_published_by` ASC),
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`fk_user_id_author`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_layer_user_1`
    FOREIGN KEY (`fk_user_id_published_by`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`changeset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`changeset` ;

CREATE TABLE IF NOT EXISTS `mydb`.`changeset` (
  `id` INT NOT NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `closed_at` TIMESTAMP NULL,
  `fk_user_id` INT NOT NULL,
  `fk_layer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_project_tb_user1_idx` (`fk_user_id` ASC),
  INDEX `fk_change_set_project1_idx` (`fk_layer_id` ASC),
  CONSTRAINT `fk_tb_project_tb_user1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_change_set_project1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`version_feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`version_feature` ;

CREATE TABLE IF NOT EXISTS `mydb`.`version_feature` (
  `id` INT NOT NULL,
  `geom` GEOMETRYCOLLECTION NOT NULL,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  `file` TEXT NULL,
  `version` INT NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  `fk_changeset_id` INT NOT NULL,
  PRIMARY KEY (`id`, `version`),
  INDEX `fk_tb_contribution_tb_project1_idx` (`fk_changeset_id` ASC),
  CONSTRAINT `fk_tb_contribution_tb_project1`
    FOREIGN KEY (`fk_changeset_id`)
    REFERENCES `mydb`.`changeset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`auth` ;

CREATE TABLE IF NOT EXISTS `mydb`.`auth` (
  `id` INT NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  `is_manager` TINYINT(1) NOT NULL,
  `is_curator` TINYINT(1) NOT NULL,
  `fk_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_user1_idx` (`fk_user_id` ASC),
  CONSTRAINT `fk_auth_user1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_layer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_layer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_layer` (
  `fk_user_id` INT NOT NULL,
  `fk_layer_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  INDEX `fk_project_subscriber_user1_idx` (`fk_user_id` ASC),
  PRIMARY KEY (`fk_user_id`, `fk_layer_id`),
  INDEX `fk_user_layer_layer1_idx` (`fk_layer_id` ASC),
  CONSTRAINT `fk_project_subscriber_user1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_layer_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`feature` ;

CREATE TABLE IF NOT EXISTS `mydb`.`feature` (
  `id` INT NOT NULL,
  `geom` GEOMETRYCOLLECTION NOT NULL,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  `file` TEXT NULL,
  `version` INT NOT NULL,
  `fk_changeset_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_contribution_tb_project1_idx` (`fk_changeset_id` ASC),
  CONSTRAINT `fk_tb_contribution_tb_project10`
    FOREIGN KEY (`fk_changeset_id`)
    REFERENCES `mydb`.`changeset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `create_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `closed_at` TIMESTAMP NULL,
  `fk_user_id` INT NOT NULL,
  `fk_layer_id` INT NOT NULL,
  `fk_parent_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_layer1_idx` (`fk_layer_id` ASC),
  INDEX `fk_review_user_1_idx` (`fk_user_id` ASC),
  INDEX `fk_layer_comment_layer_comment1_idx` (`fk_parent_id` ASC),
  CONSTRAINT `fk_review_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_layer_comment_layer_comment1`
    FOREIGN KEY (`fk_parent_id`)
    REFERENCES `mydb`.`review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`theme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`theme` (
  `id` INT NOT NULL,
  `name` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `fk_parent_id` INT NULL,
  `fk_user_id_creator` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_theme_theme1_idx` (`fk_parent_id` ASC),
  INDEX `fk_theme_user_1_idx` (`fk_user_id_creator` ASC),
  CONSTRAINT `fk_theme_theme1`
    FOREIGN KEY (`fk_parent_id`)
    REFERENCES `mydb`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_theme_user_1`
    FOREIGN KEY (`fk_user_id_creator`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `icon` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `fk_user_id` INT NULL,
  `fk_layer_id` INT NULL,
  `fk_theme_id` INT NULL,
  `fk_review_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_layer1_idx` (`fk_layer_id` ASC),
  INDEX `fk_notification_layer_review1_idx` (`fk_review_id` ASC),
  INDEX `fk_notification_theme1_idx` (`fk_theme_id` ASC),
  INDEX `fk_notification_user_1_idx` (`fk_user_id` ASC),
  CONSTRAINT `fk_notification_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_layer_review1`
    FOREIGN KEY (`fk_review_id`)
    REFERENCES `mydb`.`review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_theme1`
    FOREIGN KEY (`fk_theme_id`)
    REFERENCES `mydb`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_notification` (
  `fk_user_id` INT NOT NULL,
  `fk_notification_id` INT NOT NULL,
  `is_read` TINYINT(1) NULL,
  INDEX `fk_user_notification_user_1_idx` (`fk_user_id` ASC),
  INDEX `fk_user_notification_notification1_idx` (`fk_notification_id` ASC),
  CONSTRAINT `fk_user_notification_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_notification_notification1`
    FOREIGN KEY (`fk_notification_id`)
    REFERENCES `mydb`.`notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bulk_import`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bulk_import` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bulk_import` (
  `id` INT NOT NULL,
  `file` BLOB NULL,
  `description` TEXT NULL,
  `accepted` TINYINT(1) NULL,
  `created_at` VARCHAR(45) NULL,
  `accepted_at` VARCHAR(45) NULL,
  `fk_user_id` INT NOT NULL,
  `fk_layer_id` INT NOT NULL,
  `fk_user_id_curator` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bulk_import_user_1_idx` (`fk_user_id` ASC),
  INDEX `fk_bulk_import_layer1_idx` (`fk_layer_id` ASC),
  INDEX `fk_bulk_import_user_2_idx` (`fk_user_id_curator` ASC),
  CONSTRAINT `fk_bulk_import_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bulk_import_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bulk_import_user_2`
    FOREIGN KEY (`fk_user_id_curator`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`layer_followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`layer_followers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`layer_followers` (
  `fk_user_id` INT NOT NULL,
  `fk_layer_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  INDEX `fk_user_follows_layer_user_1_idx` (`fk_user_id` ASC),
  INDEX `fk_user_follows_layer_layer1_idx` (`fk_layer_id` ASC),
  PRIMARY KEY (`fk_user_id`, `fk_layer_id`),
  CONSTRAINT `fk_user_follows_layer_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_follows_layer_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`theme_followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`theme_followers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`theme_followers` (
  `fk_user_id` INT NOT NULL,
  `fk_theme_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  INDEX `fk_user_follows_theme_user_1_idx` (`fk_user_id` ASC),
  INDEX `fk_user_follows_theme_theme1_idx` (`fk_theme_id` ASC),
  PRIMARY KEY (`fk_theme_id`, `fk_user_id`),
  CONSTRAINT `fk_user_follows_theme_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_follows_theme_theme1`
    FOREIGN KEY (`fk_theme_id`)
    REFERENCES `mydb`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reference_`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reference_` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reference_` (
  `id` INT NOT NULL,
  `description` TEXT NULL,
  `fk_layer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reference_layer1_idx` (`fk_layer_id` ASC),
  CONSTRAINT `fk_reference_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curator` (
  `fk_user_id` INT NOT NULL,
  `fk_theme_id` INT NOT NULL,
  `region` TEXT NULL,
  `fk_user_id_creator` INT NOT NULL,
  INDEX `fk_curator_user_theme_user_1_idx` (`fk_user_id` ASC),
  INDEX `fk_curator_user_theme_theme1_idx` (`fk_theme_id` ASC),
  INDEX `fk_curator_user_1_idx` (`fk_user_id_creator` ASC),
  CONSTRAINT `fk_curator_user_theme_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curator_user_theme_theme1`
    FOREIGN KEY (`fk_theme_id`)
    REFERENCES `mydb`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curator_user_1`
    FOREIGN KEY (`fk_user_id_creator`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`layer_theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`layer_theme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`layer_theme` (
  `fk_layer_id` INT NOT NULL,
  `fk_theme_id` INT NOT NULL,
  INDEX `fk_layer_theme_layer1_idx` (`fk_layer_id` ASC),
  INDEX `fk_layer_theme_theme1_idx` (`fk_theme_id` ASC),
  CONSTRAINT `fk_layer_theme_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_layer_theme_theme1`
    FOREIGN KEY (`fk_theme_id`)
    REFERENCES `mydb`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id` INT NOT NULL,
  `body` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `fk_layer_id` INT NOT NULL,
  `fk_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_layer1_idx` (`fk_layer_id` ASC),
  INDEX `fk_comment_user_1_idx` (`fk_user_id` ASC),
  CONSTRAINT `fk_comment_layer1`
    FOREIGN KEY (`fk_layer_id`)
    REFERENCES `mydb`.`layer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user_1`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `mydb`.`user_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
